//! # 🦀 Calc Module — Example Omni-Kernel Guest (Rust → WASM)
//!
//! This is a high-performance calculation module that will be compiled
//! to WebAssembly and loaded into the Omni-Kernel runtime.
//!
//! ## Compilation
//!
//! ```bash
//! # Add the WASM target
//! rustup target add wasm32-wasip1
//!
//! # Build the module
//! cargo build --target wasm32-wasip1 --release
//! ```
//!
//! ## Exported Functions
//!
//! - `add(a: i32, b: i32) -> i32`
//! - `multiply(a: i32, b: i32) -> i32`
//! - `fibonacci(n: i32) -> i64`
//! - `matrix_dot_product(ptr: *const f64, len: i32) -> f64`

// ══════════════════════════════════════════════════════════════
// Bridge imports — these will be provided by the Omni-Kernel host.
//
// In Phase 2, these will be auto-generated by wit-bindgen from
// the WIT interface definition. For now, we declare them manually.
// ══════════════════════════════════════════════════════════════

extern "C" {
    /// Allocate memory in the Universal Memory Pool.
    fn bridge_alloc(size: i32) -> i32;
    /// Write data to the Universal Memory Pool.
    fn bridge_write(handle: i32, offset: i32, ptr: *const u8, len: i32);
    /// Read data from the Universal Memory Pool.
    fn bridge_read(handle: i32, offset: i32, ptr: *mut u8, len: i32);
    /// Call a function in another module.
    fn bridge_call(module_ptr: *const u8, module_len: i32,
                   func_ptr: *const u8, func_len: i32,
                   args_handle: i32) -> i32;
    /// Log a message to the host.
    fn bridge_log(level: i32, ptr: *const u8, len: i32);
}

// ══════════════════════════════════════════════════════════════
// Exported functions — callable by other modules via the Bridge
// ══════════════════════════════════════════════════════════════

/// Add two integers.
///
/// This is the simplest possible bridge function. When called via
/// `bridge_call("calc-module", "add", args_handle)`:
/// - args_handle contains 8 bytes: [a: i32 LE, b: i32 LE]
/// - Returns 4 bytes: [result: i32 LE]
#[no_mangle]
pub extern "C" fn add(a: i32, b: i32) -> i32 {
    a + b
}

/// Multiply two integers.
#[no_mangle]
pub extern "C" fn multiply(a: i32, b: i32) -> i32 {
    a * b
}

/// Compute the nth Fibonacci number iteratively.
///
/// This demonstrates a high-performance computation path — when this
/// module runs as WASM inside Omni-Kernel, it gets JIT-compiled to
/// native machine code by Wasmtime's Cranelift backend.
#[no_mangle]
pub extern "C" fn fibonacci(n: i32) -> i64 {
    if n <= 0 {
        return 0;
    }
    if n == 1 {
        return 1;
    }

    let mut a: i64 = 0;
    let mut b: i64 = 1;

    for _ in 2..=n {
        let temp = a + b;
        a = b;
        b = temp;
    }

    b
}

/// Compute the dot product of two vectors stored contiguously in memory.
///
/// This demonstrates how WASM modules can work with shared memory
/// efficiently — the vectors are stored in the Universal Memory Pool
/// and accessed via pointers, avoiding any serialization.
///
/// Layout: [vec_a: f64 × len, vec_b: f64 × len]
/// Total bytes: len * 8 * 2
#[no_mangle]
pub extern "C" fn dot_product(data_ptr: *const f64, len: i32) -> f64 {
    let len = len as usize;

    // Safety: In the Omni-Kernel environment, these pointers reference
    // validated regions of the Universal Memory Pool.
    unsafe {
        let vec_a = std::slice::from_raw_parts(data_ptr, len);
        let vec_b = std::slice::from_raw_parts(data_ptr.add(len), len);

        let mut sum: f64 = 0.0;
        for i in 0..len {
            sum += vec_a[i] * vec_b[i];
        }
        sum
    }
}

/// Matrix multiplication for square matrices (NxN).
///
/// Demonstrates compute-intensive operations that benefit from
/// WASM's near-native performance via Cranelift JIT compilation.
///
/// Layout: [matrix_a: f64 × n×n, matrix_b: f64 × n×n]
/// Result is written to a new shared memory block.
#[no_mangle]
pub extern "C" fn matrix_multiply(data_ptr: *const f64, n: i32) -> *const f64 {
    let n = n as usize;

    unsafe {
        let a = std::slice::from_raw_parts(data_ptr, n * n);
        let b = std::slice::from_raw_parts(data_ptr.add(n * n), n * n);

        // Allocate result via the bridge
        let result_size = (n * n * std::mem::size_of::<f64>()) as i32;
        let result_handle = bridge_alloc(result_size);

        // Create a local buffer for the result
        let mut result = vec![0.0f64; n * n];

        for i in 0..n {
            for j in 0..n {
                let mut sum = 0.0f64;
                for k in 0..n {
                    sum += a[i * n + k] * b[k * n + j];
                }
                result[i * n + j] = sum;
            }
        }

        // Write result to shared memory pool
        bridge_write(
            result_handle,
            0,
            result.as_ptr() as *const u8,
            result_size,
        );

        result.as_ptr()
    }
}

// ══════════════════════════════════════════════════════════════
// Guest lifecycle — called by the Omni-Kernel host
// ══════════════════════════════════════════════════════════════

/// Called when the module is loaded. Returns 1 for success.
#[no_mangle]
pub extern "C" fn guest_init() -> i32 {
    // In a real module, we'd register our exports with the bridge here.
    // For now, the host discovers exports via WASM introspection.
    1
}

/// Called when the module is being unloaded.
#[no_mangle]
pub extern "C" fn guest_shutdown() {
    // Clean up any resources
}
